package cmd

import (
	"github.com/caarlos0/duration"
	xstrings "github.com/charmbracelet/x/exp/strings"
)

var helpText = map[string]string{
	"api":                   "OpenAI compatible REST API (openai, localai, anthropic, ...)",
	"apis":                  "Aliases and endpoints for OpenAI compatible REST API",
	"http-proxy":            "HTTP proxy to use for API requests",
	"model":                 "Default model (gpt-3.5-turbo, gpt-4, ggml-gpt4all-j...)",
	"ask-model":             "Ask which model to use via interactive prompt",
	"max-input-chars":       "Default character limit on input to model",
	"format":                "Ask for the response to be formatted as markdown unless otherwise set",
	"format-text":           "Text to append when using the -f flag",
	"format-as":             "Format to use when formatting is enabled",
	"role":                  "System role to use",
	"roles":                 "List of predefined system messages that can be used as roles",
	"list-roles":            "List the roles defined in your configuration file",
	"prompt":                "Include the prompt from the arguments and stdin, truncate stdin to specified number of lines",
	"prompt-args":           "Include the prompt from the arguments in the response",
	"raw":                   "Render output as raw text when connected to a TTY",
	"quiet":                 "Quiet mode (hide the spinner while loading and stderr messages for success)",
	"help":                  "Show help and exit",
	"version":               "Show version and exit",
	"max-retries":           "Maximum number of times to retry API calls",
	"request-timeout":       "Maximum wall time for a single provider request/stream (0 uses default; negative disables)",
	"no-limit":              "Turn off the client-side limit on the size of the input into the model",
	"word-wrap":             "Wrap formatted output at specific width (default is 80)",
	"max-tokens":            "Maximum number of tokens in response",
	"max-completion-tokens": "Maximum number of completion tokens in response",
	"temp":                  "Temperature (randomness) of results, from 0.0 to 2.0, -1.0 to disable",
	"stop":                  "Stop sequences (currently not forwarded by Fantasy v0.8.1 in yai bridge)",
	"topp":                  "TopP, an alternative to temperature that narrows response, from 0.0 to 1.0, -1.0 to disable",
	"topk":                  "TopK, only sample from the top K options for each subsequent token, -1 to disable",
	"fanciness":             "Your desired level of fanciness",
	"status-text":           "Text to show while generating",
	"settings":              "Open settings in your $EDITOR",
	"dirs":                  "Print the directories in which yai stores its data",
	"reset-settings":        "Backup your old settings file and reset everything to the defaults",
	"continue":              "Continue from the last response or a given save title",
	"continue-last":         "Continue from the last response",
	"no-cache":              "Disables caching of the prompt/response",
	"title":                 "Saves the current conversation with the given title",
	"list":                  "Lists saved conversations",
	"delete":                "Deletes one or more saved conversations with the given titles or IDs",
	"delete-older-than":     "Deletes all saved conversations older than the specified duration; valid values are " + xstrings.EnglishJoin(duration.ValidUnits(), true),
	"show":                  "Show a saved conversation with the given title or ID",
	"theme":                 "Theme to use in the forms; valid choices are charm, catppuccin, dracula, and base16",
	"show-last":             "Show the last saved conversation",
	"editor":                "Edit the prompt in your $EDITOR; only taken into account if no other args and if STDIN is a TTY",
	"mcp-servers":           "MCP Servers configurations",
	"mcp-disable":           "Disable specific MCP servers",
	"mcp-list":              "List all available MCP servers",
	"mcp-list-tools":        "List all available tools from enabled MCP servers",
	"mcp-timeout":           "Timeout for MCP server calls, defaults to 15 seconds",
	"mcp-allow-non-tty":     "Allow MCP tool exposure/execution when STDIN is not a TTY (disabled by default)",
	"mcp-no-inherit-env":    "Do not inherit the full process environment for stdio MCP servers",
}
